WEEKDAY_PROJEKTRON_TASK_COLUMN = 'A'
WEEKDAY_JIRA_TICKET_COLUMN = 'B'
WEEKDAY_DATE_CELL = 'B1'
WEEKDAY_COMMENT_COLUMN = 'C'
WEEKDAY_TIME_COLUMN = 'D'
WEEKDAY_JIRA_TICKET_DESCRIPTON_RANGE = "D3:D53"
WEEKDAY_JIRA_TICKET_NUMBER_RANGE = "E3:E53"
WEEKDAY_CONSOLE_OUTPUT_CELL = 'E27'
WEEKDAY_JIRA_STATUS_COLUMN = 'K'
WEEKDAY_PROJEKTRON_STATUS_COLUMN = 'L'
PROJI_SETTINGS_EMAIL_COLUMN = 'C'
PROJI_SETTINGS_JIRA_TICKET_MAPPING_COLUMN = 'F'
PROJI_SETTINGS_JIRA_HOST_COLUMN = 'B'
PROJI_SETTINGS_ONE_PASSWORD_REFERENCE_JIRA_COLUMN = 'D'

EMAIL_CELL = 'H4'
ONE_PASSWORD_REFERENCE_PROJEKTRON_CELL = 'H7'               # TODO: Use ProjiSettingsSheet
AUTOCOMPLETE_JIRA_TICKET_DESCRIPTION_CELL = 'H13'           # TODO: Use ProjiSettingsSheet
BOOK_COMMENTS_TO_JIRA_CHECK_CELL = 'H14'                    # TODO: Use ProjiSettingsSheet
PROJEKTRON_DOMAIN_CELL = 'H17'                              # TODO: Use ProjiSettingsSheet
HEADLESS_MODE_CELL = 'H18'                                  # TODO: Use ProjiSettingsSheet
LOG_ONE_PASSWORD_ROUTINE_CELL = 'H19'                       # TODO: Use ProjiSettingsSheet
PROJEKTRON_LOCALE_SETTING_CELL = 'H20'                      # TODO: Use ProjiSettingsSheet

VBA_SHEET_CONSOLE_OUTPUT_CELL = 'G27'
VBA_SHEET_SESSION_TOKEN_CELL = 'H5'
VBA_SHEET_PASSWORD_TOKEN_TIMESTAMP_CELL = 'K5'
VBA_SHEET_STATUS_OF_SESSION_TOKEN_CELL = "L5"
VBA_SHEET_REPO_STATUS_CELL = "K23"

WORKBOOK_NAME = '../../data/TimeBooking.xlsm'
VBA_SETTINGS_SHEET_NAME = 'VBA-Settings'
PRO_JI_SETTINGS = 'ProJi-Settings'

